spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    orders-to-be-completed: orders-to-be-completed
    orders-completed-conversion-of-mass: orders-conversion-of-mass
    orders-completed-foundry: orders-completed-foundry

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG